version: '3.1'

services:

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
        - "14330:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"