namespace UserLookupService.Abstractions
{
    public enum State
    {
        None = 0,
        Alabama = 1,
        Alaska = 2,
        Arizona = 3,
        Arkansas = 4,
        California = 5,
        Colorado = 6,
        Connecticut = 7,
        Delaware = 8,
        Florida = 9,
        Georgia = 10,
        Hawaii = 11,
        Idaho = 12,
        Illinois = 13,
        Indiana = 14,
        Iowa = 15,
        Kansas = 16,
        Kentucky = 17,
        Louisiana = 18,
        Maine = 19,
        Maryland = 20,
        Massachusetts = 21,
        Michigan = 22,
        Minnesota = 23,
        Mississippi = 24,
        Missouri = 25,
        Montana = 26,
        Nebraska = 27,
        Nevada = 28,
        NewHampshire = 29,
        NewJersey = 30,
        NewMexico = 31,
        NewYork = 32,
        NorthCarolina = 33,
        NorthDakota = 34,
        Ohio = 35,
        Oklahoma = 36,
        Oregon = 37,
        Pennsylvania = 38,
        RhodeIsland = 39,
        SouthCarolina = 40,
        SouthDakota = 41,
        Tennessee = 42,
        Texas = 43,
        Utah = 44,
        Vermont = 45,
        Virginia = 46,
        Washington = 47,
        WestVirginia = 48,
        Wisconsin = 49,
        Wyoming = 50,
    }
}
